### ISSUE TITLE
Error: Could not start binwalk (ModuleNotFoundError: No module named 'pwd') on opening binary analysis

### ISSUE THREAD

**Issue by tankirules** [gcarmix/HexWalk#39]
I'm on windows 10, and from some googling it seems 'pwd' isn't a module used on windows python?
I get this error when trying to do binary analysis on an image(hexwalk starts up fine)

Could not start binwalk.
Error: 
Traceback (most recent call last):
  File "C:\Users\tankirules\HexWalk\win64\binw.py", line 6, in <module>
    binwalk.scan('--signature', sys.argv[1])
  File "C:\Users\tankirules\AppData\Local\Programs\Python\Python310\lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\__init__.py", line 10, in scan
    objs = m.execute()
  File "C:\Users\tankirules\AppData\Local\Programs\Python\Python310\lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\core\module.py", line 782, in execute
    for module in self.list():
  File "C:\Users\tankirules\AppData\Local\Programs\Python\Python310\lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\core\module.py", line 699, in list
    import binwalk.modules
  File "C:\Users\tankirules\AppData\Local\Programs\Python\Python310\lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\modules\__init__.py", line 16, in <module>
    from binwalk.modules.extractor import Extractor
  File "C:\Users\tankirules\AppData\Local\Programs\Python\Python310\lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\modules\extractor.py", line 7, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by gcarmix** [comment]
It seems that you are not using the binwalk that is provided with hexwalk distribution. On Windows it is fundamental since the vanilla binwalk is somewhat broken on Windows. Let me know if you solve it
